[package]
name = "zoea"
version = "0.1.0"
authors = ["Fabio Mencoboni <Fabio.Mencoboni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahash = "4.0.0"
curl = "0.4.29"
rust-stemmers = "1.2.0"
